"""add output_video_path to project

Revision ID: 2e62e66c72f7
Revises: ebaddaf6766f
Create Date: 2026-04-17 01:40:56.271090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e62e66c72f7'
down_revision: Union[str, None] = 'ebaddaf6766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('output_video_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'output_video_path')
    # ### end Alembic commands ###
