"""add_analysis_status_to_kb_cases

Revision ID: 3c4cfad6bbde
Revises: 2e62e66c72f7
Create Date: 2026-04-17 02:31:17.947239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4cfad6bbde'
down_revision: Union[str, None] = '2e62e66c72f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_cases', sa.Column('analysis_status', sa.String(length=20), nullable=True))
    op.add_column('kb_cases', sa.Column('celery_task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_cases', 'celery_task_id')
    op.drop_column('kb_cases', 'analysis_status')
    # ### end Alembic commands ###
