"""add dialog fields to shot

Revision ID: d030eb8ab794
Revises: a1b2c3d4e5f6
Create Date: 2026-04-22 03:30:54.863755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd030eb8ab794'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('dialog', sa.Text(), nullable=True))
    op.add_column('shots', sa.Column('dialog_lang', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'dialog_lang')
    op.drop_column('shots', 'dialog')
    # ### end Alembic commands ###
